version: 2

builds:
  - id: bamgate
    main: ./cmd/bamgate
    binary: bamgate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: bamgate-hub
    main: ./cmd/bamgate-hub
    binary: bamgate-hub
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - ids:
      - bamgate
    repository:
      owner: bamgate
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/bamgate/bamgate"
    description: "WireGuard VPN tunnel over WebRTC"
    license: "MIT"
    install: |
      bin.install "bamgate"
    test: |
      system "#{bin}/bamgate", "--version"
