version: 2

builds:
  - id: bamgate
    main: ./cmd/bamgate
    binary: bamgate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: bamgate-hub
    main: ./cmd/bamgate-hub
    binary: bamgate-hub
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: bamgate
    ids:
      - bamgate
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
  - id: bamgate-hub
    ids:
      - bamgate-hub
    formats:
      - tar.gz
    name_template: >-
      bamgate-hub_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"


