package webrtc

import (
	"github.com/pion/webrtc/v4"
)

// DefaultSTUNServers are public STUN servers used for NAT discovery.
var DefaultSTUNServers = []string{
	"stun:stun.cloudflare.com:3478",
	"stun:stun.l.google.com:19302",
}

// ICEConfig holds the ICE server configuration for a peer connection.
type ICEConfig struct {
	// STUNServers is a list of STUN server URLs (e.g. "stun:stun.l.google.com:19302").
	STUNServers []string

	// TURNServers is a list of TURN server configurations.
	// Empty until Phase 4 (TURN relay on Cloudflare Workers).
	TURNServers []TURNServer
}

// TURNServer describes a single TURN server with credentials.
type TURNServer struct {
	// URL is the TURN server URL (e.g. "turn:my-turn.example.com:443?transport=tcp").
	URL string

	// Username is the TURN username (time-limited, generated by the signaling server).
	Username string

	// Credential is the TURN credential (HMAC-derived from shared secret).
	Credential string
}

// DefaultICEConfig returns an ICEConfig with the default public STUN servers
// and no TURN servers.
func DefaultICEConfig() ICEConfig {
	return ICEConfig{
		STUNServers: DefaultSTUNServers,
	}
}

// pionICEServers converts the ICEConfig to pion's []webrtc.ICEServer format.
func (c ICEConfig) pionICEServers() []webrtc.ICEServer {
	var servers []webrtc.ICEServer

	if len(c.STUNServers) > 0 {
		servers = append(servers, webrtc.ICEServer{
			URLs: c.STUNServers,
		})
	}

	for _, turn := range c.TURNServers {
		servers = append(servers, webrtc.ICEServer{
			URLs:       []string{turn.URL},
			Username:   turn.Username,
			Credential: turn.Credential,
		})
	}

	return servers
}
